Fix/issues 5
IgorGanapolsky/android-watch-app pull request #5
Opened 2019-03-13 19:27 UTC by alex-melnyk

2019-03-13 19:30 UTC, IgorGanapolsky commented
What is the description of this pull request, and how does it relate to "Modifications Applied" pull request?

2019-03-14 14:37 UTC, IgorGanapolsky commented
Unable to launch app.  Crash:
> E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: com.igorganapolsky.vibratingwatchapp, PID: 3241
    java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
        at android.arch.persistence.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:135)
        at android.arch.persistence.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:115)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:151)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:310)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:194)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:96)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:54)
        at android.arch.persistence.room.RoomDatabase.compileStatement(RoomDatabase.java:244)
        at android.arch.persistence.room.SharedSQLiteStatement.createNewStatement(SharedSQLiteStatement.java:65)
        at android.arch.persistence.room.SharedSQLiteStatement.getStmt(SharedSQLiteStatement.java:72)
        at android.arch.persistence.room.SharedSQLiteStatement.acquire(SharedSQLiteStatement.java:87)
        at com.igorganapolsky.vibratingwatchapp.domain.local.TimersDao_Impl.disableAll(TimersDao_Impl.java:155)
        at com.igorganapolsky.vibratingwatchapp.domain.WatchRepository.lambda$disableAll$5(WatchRepository.java:67)
        at com.igorganapolsky.vibratingwatchapp.domain.-$$Lambda$WatchRepository$UOke5DJ4yvgXckQg-vyJI_madU8.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

2019-03-14 14:38 UTC, IgorGanapolsky requested changes
.

2019-03-15 14:23 UTC, IgorGanapolsky commented on app/src/main/java/com/igorganapolsky/vibratingwatchapp/VibratingWatchApp.java
> +import java.util.concurrent.ThreadPoolExecutor;
unused import

2019-03-15 14:24 UTC, IgorGanapolsky commented
Explain difference between **core** package and **domain** package

2019-03-15 14:26 UTC, IgorGanapolsky commented on app/src/main/java/com/igorganapolsky/vibratingwatchapp/core/util/ViewModelFactory.java
> +    private CountdownManager countdownManager;
can be `final` vars

2019-03-15 14:26 UTC, IgorGanapolsky commented on app/src/main/java/com/igorganapolsky/vibratingwatchapp/domain/WatchRepository.java
> +    private ExecutorService executor;
can be `final` vars

2019-03-15 14:27 UTC, IgorGanapolsky commented on app/src/main/java/com/igorganapolsky/vibratingwatchapp/domain/local/TimersDao.java
> +    LiveData<TimerEntity> observeById(int id);
Where is this method used?

2019-03-15 14:28 UTC, IgorGanapolsky commented on app/src/main/java/com/igorganapolsky/vibratingwatchapp/domain/model/BuzzSetup.java
> +    private int buzzTime;
can be `final` vars

2019-03-15 14:28 UTC, IgorGanapolsky commented on app/src/main/java/com/igorganapolsky/vibratingwatchapp/domain/model/CountData.java
> +    public void setAnimationNeeded(boolean animationNeeded) {
where is this method used?

2019-03-15 14:28 UTC, IgorGanapolsky commented on app/src/main/java/com/igorganapolsky/vibratingwatchapp/domain/model/TimerModel.java
> +    public TimerModel(int hours, int minutes, int seconds) {
can be `private`

2019-03-15 14:29 UTC, IgorGanapolsky commented on app/src/main/java/com/igorganapolsky/vibratingwatchapp/manager/timer/CountdownManager.java
> +    boolean isHasMoreRepeats();
what is the purpose of this method?

2019-03-15 14:31 UTC, IgorGanapolsky commented
Would it make sense to put **manager** and **vibration** packages in domain or core?  Or perhaps make them into separate gradle modules.  I'm trying to understand the architecture that is followed here...

2019-03-15 14:33 UTC, IgorGanapolsky commented
Thank you for externalizing values into **strings.xml** and **dimens.xml** 👍

2019-03-15 14:38 UTC, IgorGanapolsky commented
Let's improve the speed of launching these screens:
https://drive.google.com/open?id=1hAE9OoLJpF2tK_rFMofIkjJv2Y1hT02J

2019-03-15 14:40 UTC, IgorGanapolsky commented
Unable to tap on the RecyclerView elements:
https://drive.google.com/open?id=1-68aY5WvOb2nuAuC90I3MvZFGBDzMg78

2019-03-15 14:41 UTC, IgorGanapolsky requested changes
Please address PR remarks

2019-03-15 21:02 UTC, IgorGanapolsky commented
Looks like this circle dot
![device-2019-03-15-170132](https://user-images.githubusercontent.com/201209/54461830-26741200-4744-11e9-8358-0c6bc9732e0c.png)
 doesn't accurately reflect the number:

2019-03-15 21:08 UTC, IgorGanapolsky commented
Another request: is it possible to make swiping left-to-right on this screen easier?  Right now, the user cannot exit this screen unless they carefully swipe in the proper area:
https://drive.google.com/open?id=1khwpmK7XtqBKefkwXsKkMk_nWj-OW9WV

2019-03-15 21:15 UTC, IgorGanapolsky commented
Pressing the stop button a running timer should reset it to the correct value, not **### 00:00:00**:
https://drive.google.com/open?id=1NuIJH9BXJ0sgW6M-8Xl8jSjda_LZMveg

2019-03-15 21:20 UTC, IgorGanapolsky commented
Looks like the reset button completely doesn't work:
https://drive.google.com/open?id=1PdfXPEzejdQgkWnUN5b61XIqTU6E7F8s

2019-03-15 21:38 UTC, IgorGanapolsky commented
Shouldn't there be indicators on this screen to tell the user which timer is running and which is not?
![device-2019-03-15-173652](https://user-images.githubusercontent.com/201209/54463326-1579cf80-4749-11e9-84ba-a49025c721fc.png)

2019-03-17 18:52 UTC, IgorGanapolsky commented
Another issue: when the timer buzzes, user is not brought to the screen to see it or stop it.  Instead, the watch screens remains off, or whatever other app is open at that time, and the watch is buzzing.

Expected behavior: just like any good timer app, a triggered timer should open the triggered timer screen for the user
Actual behavior: nothing happens other than the watch is buzzing

2019-03-17 18:58 UTC, IgorGanapolsky commented
There is also a warning in Logcat:
> W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.igorganapolsky.vibratingwatchapp flg=0x4000010 (has extras) } to com.android.vending/com.google.android.finsky.packagemanager.impl.PackageMonitorReceiverImpl$RegisteredReceiver

2019-03-17 19:07 UTC, IgorGanapolsky commented
Incorrect flow in the app.  Steps to reproduce:
1) Create two timers
2) Launch/start timer from Timers List screen
3) Go back to Timers List screen
4) Open the other timer, edit its settings

**Expected result:**
you should be back on Timers List screen
**Actual result:**
you are on the first timer's activation/status screen

2019-03-17 19:16 UTC, IgorGanapolsky commented
The **stop** button doesn't work:
https://drive.google.com/open?id=1YsZp95Fu3Mt9BXjWpz4fnU1xX59ItAPG

2019-03-17 19:16 UTC, IgorGanapolsky commented
Warnings like this should be fixed:
>  W/ActivityManager: Duplicate finish request for ActivityRecord{4d90de9 u0 com.igorganapolsky.vibratingwatchapp/.presentation.main.TimerListActivity

2019-03-17 19:21 UTC, IgorGanapolsky commented
This warning should be fixed:
>  W/ActivityManager: Activity pause timeout for ActivityRecord{d9d18a1 u0 com.igorganapolsky.vibratingwatchapp/.presentation.settings.SetTimerActivity

2019-03-17 19:21 UTC, IgorGanapolsky commented
Why is Logcat showing this?
> I/Choreographer: Skipped 46 frames!  The application may be doing too much work on its main thread.

What is going on the main thread?

2019-03-17 19:23 UTC, IgorGanapolsky commented
Another issue:
after editing a timer's config, the app goes back go config screen (instead of Timers List screen)

2019-03-17 19:41 UTC, IgorGanapolsky commented
What the heck is going on here???
https://drive.google.com/open?id=1QXG_C2660u-9pK0GR9O3NG6LKwrxgtZw

2019-03-18 10:31 UTC, yuliiatereshchenko commented
> Looks like this **circle dot** doesn't accurately reflect the number:
> ![device-2019-03-15-170132](https://user-images.githubusercontent.com/201209/54461830-26741200-4744-11e9-8358-0c6bc9732e0c.png)
> 
> Also, can we make this **circle dot** bigger? It is difficult for the user to drag it now.

1 the circle dot reflect the current number for H. the current H number is less than 1, that is why it reflect 0
2 yes,  but its an improvement

2019-03-18 10:42 UTC, yuliiatereshchenko commented
> Looks like the **reset** button completely doesn't work:
> https://drive.google.com/open?id=1PdfXPEzejdQgkWnUN5b61XIqTU6E7F8s

1 please, could you specify which journey describes behaviour of this button?

2019-03-18 11:10 UTC, yuliiatereshchenko commented
> Another issue: when the timer buzzes, user is currently not brought to the screen to _see it_ or _stop it_. Instead, the watch screen remains off, or on whatever other app is open at that time, and the watch is buzzing.
> 
> **Expected behavior:** just like any good timer app, a triggered timer should open the triggered timer screen for the user
> **Actual behavior:** nothing happens other than the watch is buzzing

1 please, could you specify which journey describes that it should be brought to the screen to _see it_ or _stop it_?

2019-03-18 11:36 UTC, yuliiatereshchenko commented
> after editing a timer's config, the app goes back to config screen (instead of Timers List screen)

1 there is no information in Journey 13 where should be user redirected after configuration is done

2019-06-13 19:54 UTC, IgorGanapolsky commented on app/build.gradle
> +    implementation 'com.google.android.material:material:1.0.0'
```what is this```

2020-03-07 00:37 UTC, merged